### ISSUE TITLE
能否实现 docker container 在不同 D1 上的自动迁移？

### ISSUE THREAD

**Issue by lazyparser** [plctlab/riscv-lab-access#2]
现在有 1000 个D1，每个D1上可以跑1-10个container。

我们希望每个用户尽可能独占一个D1。当用户数量小于设别数量的时候，我们可以将每个D1上的container数量限制在1。

那么当用户数量超过1000的时候，就需要进行动态的分配。

这个issue用于跟踪可能的做法。

业界应该已经有几套成熟的做法，但是需要考虑到D1/RISC-V的性能，以及 lab 本身迁移次数频率很低的特点，尽可能降低技术实现的复杂度。

**Comment by mengzhuo** [comment]
k8s 有podAffinity ，可以设置成软性反亲和其他所有pod。

**Comment by lazyparser** [comment]
Thanks 👌
