### ISSUE TITLE
LLVM project accessibility (github)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [plctlab/riscv-lab-access#44]
Christ Jesus bless you.

> advancedwebdeveloper@ubuntu:~$ git clone https://github.com/llvm/llvm-project
> Cloning into 'llvm-project'...
> fatal: unable to access 'https://github.com/llvm/llvm-project/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
 
I got the issue, as described above.

Perhaps you might arrange (or specify an existing, if any) git mirror of LLVM project, accessible at Chinese servers?

God bless you.

**Comment by lazyparser** [comment]
Two solutions:

1. use a mirror for the initial clone, e.g. https://gitee.com/mirror/llvm
2. use a proxy on the unmatched board. E.g. `export HTTPS_PROXY=HTTP://127.0.0.1:8080` (need more configurations).

I guess the issue had been solved after the conversation in the RVI Slack. So close it.
